### ISSUE TITLE
Getting syntax within the library when building

### ISSUE THREAD

**Issue by rc8marcelo** [sebkoller/certificate_pinning_httpclient#4]
Hi,

I'm trying to run the package on Flutter 2.5.4. I'm not sure what the minimum version is since on pub.dev it says the minimum version is Dart 2.14. When trying to run my test app with this integrated, I get the following errors when I try to debug:

![image](https://user-images.githubusercontent.com/341493/215034809-e2ef3a68-d185-4da3-89a1-605166e220d3.png)

**Comment by sebkoller** [comment]
The minimum version is actually wrong. The minimum supported Dart version is probably 2.17.3.

**Comment by rc8marcelo** [comment]
Yeah, I think the minimum Flutter version to get this to work is 3. Kinda sad, we can't move to 3 just yet haha. I'll close the issue now since it's just an incorrect minimum version. Thanks.
