### ISSUE TITLE
example for httpclient

### ISSUE THREAD

**Issue by nashihu** [sebkoller/certificate_pinning_httpclient#5]
in pub.dev the example currently support for dio. does it support for HttpClient ? thank you

**Comment by sebkoller** [comment]
Yes, this package actually is an implementation of an HttpClient.
So when you construct it with `CertificatePinningHttpClient(...)` you get an HttpClient.

If you don't need the low-level API of the HttpClient, I recommend that you use an IOClient (part of the official http package), as stated in the readme.

**Comment by nashihu** [comment]
i see, got it, thanks for reply
